apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: sh24-storage-account-app
spec:
  application: sh24
  container:
    containers:
    - env:
      - fromCloudResourceOutput:
          componentName: sh24-storage-account
          output: PRIMARY_ACCESS_KEY
        name: AZURE_STORAGE_KEY
      - fromCloudResourceOutput:
          componentName: sh24-storage-account
          output: NAME
        name: AZURE_STORAGE_ACCOUNT_NAME
      - fromCloudResourceOutput:
          componentName: sh24-storage-account
          output: CONTAINER_NAME
        name: AZURE_CONTAINER_NAME
      image: ghcr.io/appvia/azure-demo-storage-account-app:sha-ba2942dda4894ce377137d47996d392e1ae72b38
      name: ui
      ports:
      - containerPort: 3002
        name: ui
        protocol: TCP
      securityContext:
        runAsGroup: 1002
        runAsUser: 1002
    expose:
      container: ui
      port: 3002
    tls: true
  dependsOn:
  -  sh24-storage-account
  name: sh24-storage-account-app
  type: Container