apiVersion: app.appvia.io/v2beta1
kind: AppEnv
metadata:
  name: sh24-dev
spec:
  name: dev
  stage: nonprod
  application: sh24
  cloud: azure
  clusterRef:
    group: compute.appvia.io
    kind: Cluster
    name: aks-nusml
    namespace: ws-demo
    version: v2beta1